### ISSUE TITLE
Heroku app is down

### ISSUE THREAD

**Issue by jagthedrummer** [rajasegar/ruby-ast-explorer#71]
I was hoping to do some AST exploring but the app seems to be down currently.

![CleanShot 2023-09-06 at 09 51 52](https://github.com/rajasegar/ruby-ast-explorer/assets/58702/5237eeda-f6c7-407f-9c8e-c3e44272d04e)

**Comment by samdturner** [comment]
+1 I tried cloning and deploying to heroku, but ran into an error.

```
remote:        Traceback (most recent call last):
remote:          File "/tmp/build_026184fd/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
remote:            sys.exit(gyp.script_main())
remote:          File "/tmp/build_026184fd/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
remote:            return main(sys.argv[1:])
remote:          File "/tmp/build_026184fd/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
remote:            return gyp_main(args)
remote:          File "/tmp/build_026184fd/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
remote:            options.duplicate_basename_check)
remote:          File "/tmp/build_026184fd/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
remote:            params['parallel'], params['root_targets'])
remote:          File "/tmp/build_026184fd/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2783, in Load
remote:            variables, includes, depth, check, True)
remote:          File "/tmp/build_026184fd/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 399, in LoadTargetBuildFile
remote:            includes, True, check)
remote:          File "/tmp/build_026184fd/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 271, in LoadOneBuildFile
remote:            aux_data, includes, check)
remote:          File "/tmp/build_026184fd/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 308, in LoadBuildFileIncludesIntoDict
remote:            LoadOneBuildFile(include, data, aux_data, None, False, check),
remote:          File "/tmp/build_026184fd/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 251, in LoadOneBuildFile
remote:            None)
remote:          File "/app/.node-gyp/20.9.0/include/node/common.gypi", line 1
remote:            nerate ',
```
